version: '3.7'

services:
  axon-spring-cloud-stream-demo-kafka-source:
    image: axon-spring-cloud-stream-demo-kafka-source
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://axon-spring-cloud-stream-demo-source-db:5432/demo
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=thepassword
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - AXON_AXONSERVER_SERVERS=axon-server-source
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
    ports:
      - '8085:8085'
    depends_on:
      - axon-spring-cloud-stream-demo-source-db
      - axon-server-source
      - kafka
  axon-spring-cloud-stream-demo-kafka-sink:
    image: axon-spring-cloud-stream-demo-kafka-sink
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://axon-spring-cloud-stream-demo-sink-db:5432/demo
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=thepassword
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - AXON_AXONSERVER_SERVERS=axon-server-sink
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
    ports:
      - '8080:8080'
    depends_on:
      - axon-spring-cloud-stream-demo-sink-db
      - axon-server-sink
      - kafka
  axon-spring-cloud-stream-demo-source-db:
    image: postgres
    environment:
      - POSTGRES_DB=drestaurant
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=thepassword
  axon-spring-cloud-stream-demo-sink-db:
    image: postgres
    environment:
      - POSTGRES_DB=drestaurant
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=thepassword
  axon-server-source:
    image: axoniq/axonserver
    environment:
      - AXONSERVER_NAME=axon-server-source
      - AXONSERVER_HOSTNAME=axon-server-source
    ports:
      - '8024:8024'
      - '8124:8124'
  axon-server-sink:
    image: axoniq/axonserver
    environment:
      - AXONSERVER_HOSTNAME=axon-server-sink
      - AXONSERVER_NAME=axon-server-sink
    ports:
      - '8025:8024'
      - '8125:8124'
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: bootiful-dress-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: bootiful-dress-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper

